version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYAPP_DATABASE_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  web:
    build: .
    container_name: web
    volumes:
      - .:/app
      - gem_data:/usr/local/bundle
    working_dir: /app/src
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db 
    tty: true
    stdin_open: true

volumes:
  gem_data:
  db-volume:
